---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config: .eslintrc.js
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- config/
- tests/
- vendor/
- dist/
- public/
- vendor/